### ISSUE TITLE
Getting the mod to work with Terra

### ISSUE THREAD

**Issue by timephy** [yungnickyoung/Better-Caves#144]
Hi

First of all, i love how all the YUNGs-* mods make various aspects of Minecraft better.

But since i also love an overhaul of Minecraft's "above-ground" terrain, i would like to use [Terra](https://www.curseforge.com/minecraft/mc-mods/terra-world-generator), a world generation mod.

Question:
Is there a possibility to get YUNGs-* generation to work on a custom terrain generator like Terra?
Is there a config i didn't find or anything?
Note that Terra does do custom caves on its own, but it is not nearly as nice as YUNGs-*, therefore i would like to override it.

My Info:
I would like to play on 1.16.5, since that is the current state of Terra and i use Fabric.

Thanks
Tim

**Comment by yungnickyoung** [comment]
I think the Terra config has some options you can set.

For caves:
```
disable:
  carving: true # turn *off* terra caves

vanilla:
  caves: true # turn *on* vanilla caves
```

For structures:
```
disable:
  structures: true

vanilla:
  structures: true
```

If this doesn't work, I would ask in the Terra Discord.
